options:
  tmp_dir: /var/tmp
shared:
  domain: uds.local
variables:
  postgres-operator:
    POSTGRESQL:
      enabled: true
      teamId: "uds"
      volume:
        size: "30Gi"
      numberOfInstances: 1
      users:
        keycloak.keycloak: []  # database owner
        mattermost.mattermost: []
      databases:
        keyblockdb: keycloak.keycloak
        mattermostdb: mattermost.mattermost
      version: "14"
      ingress:
        - remoteNamespace: keycloak
        - remoteNamespace: mattermost